// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjmxhBVRxFo6mE_45TqU3FiRLv0F9iGPs',
    appId: '1:362041200744:web:4f3804da906fe76791abdd',
    messagingSenderId: '362041200744',
    projectId: 'laundry-guru-50b7a',
    authDomain: 'laundry-guru-50b7a.firebaseapp.com',
    databaseURL: 'https://laundry-guru-50b7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundry-guru-50b7a.appspot.com',
    measurementId: 'G-DGYX067HRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZN5nMHQNUzbOKVT1OukMQJyEhTs-U0iU',
    appId: '1:362041200744:android:99aeb57841ad29f991abdd',
    messagingSenderId: '362041200744',
    projectId: 'laundry-guru-50b7a',
    databaseURL: 'https://laundry-guru-50b7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundry-guru-50b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg8hnqpBj5haFJfJmuTfCDkKnPvJOtFBs',
    appId: '1:362041200744:ios:4cda4409c9edd18791abdd',
    messagingSenderId: '362041200744',
    projectId: 'laundry-guru-50b7a',
    databaseURL: 'https://laundry-guru-50b7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundry-guru-50b7a.appspot.com',
    androidClientId: '362041200744-r8gjr06du4rnmjusg2frj22n7k4vt57h.apps.googleusercontent.com',
    iosClientId: '362041200744-1hlmgdok5stp54cksvtr0o4gu2biln26.apps.googleusercontent.com',
    iosBundleId: 'com.example.washlyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg8hnqpBj5haFJfJmuTfCDkKnPvJOtFBs',
    appId: '1:362041200744:ios:4cda4409c9edd18791abdd',
    messagingSenderId: '362041200744',
    projectId: 'laundry-guru-50b7a',
    databaseURL: 'https://laundry-guru-50b7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundry-guru-50b7a.appspot.com',
    androidClientId: '362041200744-r8gjr06du4rnmjusg2frj22n7k4vt57h.apps.googleusercontent.com',
    iosClientId: '362041200744-1hlmgdok5stp54cksvtr0o4gu2biln26.apps.googleusercontent.com',
    iosBundleId: 'com.example.washlyMobile',
  );
}
